version: "3"
networks:
  jenkins:

volumes:
  docker-certs:
  data:

services:
  docker:
    image: docker:dind
    privileged: true
    volumes:
      - docker-certs:/certs/client
      - data:/var/jenkins_home
    ports:
      - "2376:2376"
    environment:
      DOCKER_TLS_CERTDIR: /certs
    networks:
      jenkins:
        aliases:
          - docker
  jenkins:
    build:
      context: ./jenkins
    depends_on:
      - docker
    ports:
      - "8080:8080"
      - "50000:50000"
    env_file: .env
    environment:
      DOCKER_HOST: "tcp://docker:2376"
      DOCKER_CERT_PATH: "/certs/client"
      DOCKER_TLS_VERIFY: "1"

    # secrets:
    #   - jenkins-user
    #   - jenkins-password
    networks:
      jenkins: {}

    volumes:
      - data:/var/jenkins_home
      - docker-certs:/certs:ro
      - ./jenkins/secrets.properties:/run/secrets/secrets.properties
